//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("VKFoodArea")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0+3c7c5a4d07b7d5be986a7fa5a897dbae05d42e71")]
[assembly: System.Reflection.AssemblyProductAttribute("VKFoodArea")]
[assembly: System.Reflection.AssemblyTitleAttribute("VKFoodArea")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly: System.Runtime.Versioning.TargetPlatformAttribute("Android36.0")]
[assembly: System.Runtime.Versioning.SupportedOSPlatformAttribute("Android21.0")]

// Generated by the MSBuild WriteCodeFragment class.

